site_name: Peterborough Chess Club
site_url: https://peterboroughchessclub.github.io/site/
site_author: Doug Redden

# Repository
repo_name: peterboroughchessclub/peterboroughchessclub
repo_url: https://github.com/peterboroughchessclub/site

theme:
    name: material
    custom_dir: docs/templates_overrides    
    palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/favicon.png
    icon:
      logo: logo 

    features:
      # - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      # - navigation.indexes
      - navigation.instant
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - toc.integrate
   
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true



# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peterboroughchessclub
    - icon: fontawesome/brands/facebook 
      link: www.facebook.com/peterboroughchessclub/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peterboroughchessclub
nav:
    - Introduction: index.md
    - Competitions: competitions.md
    - History: history.md
    - Tutorial: tutorials.md
    - Submit pgn: submitpgn.md
    - Game of the week: GameOfTheWeek.md
    - Software skills: websiteDevelopmentIdeas.md
    - Contact us: contactus.md
