site_name: Peterborough Chess Club

theme:
    name: material
    custom_dir: docs/templates_overrides    
palette:
    - scheme: default
      primary: stylesheets/extra.css
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
plugins:
  - search
  - mkdocs-video
social:
    - icon: fontawesome/brands/facebook 
      link: www.facebook.com/peterboroughchessclub/?locale=en_GB 
nav:
    - Introduction: index.md
    - Competions: competions.md
    - History: history.md
    - Tutorial: tutorials.md
    - Links: links.md